spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

discord:
  token: ${DISCORD_TOKEN}
