spring:
  datasource:
    url: ${URL}
    password: ${PASSWORD}
    username: ${USERNAME}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

discord:
  token: ${DISCORD_TOKEN}
